# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.blocks.images
import home.blocks.simulationexamples
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('body_en', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'code', home.blocks.simulationexamples.SimulationExampleChooserBlock()), (b'image', home.blocks.images.APIImageChooserBlock())])),
                ('body_es', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'code', home.blocks.simulationexamples.SimulationExampleChooserBlock()), (b'image', home.blocks.images.APIImageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('body_en', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('body_es', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SimulationExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[(b'EXPRESSION', b'Expression'), (b'PYTHON', b'Python')], max_length=10)),
                ('code', models.TextField()),
                ('universe', models.CharField(choices=[(b'TOP3000', b'TOP3000'), (b'TOP2000', b'TOP2000')], max_length=10)),
            ],
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
    ]
