# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 21:00
from __future__ import unicode_literals

from django.db import migrations
import home.blocks.images
import home.blocks.simulationexamples
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180110_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_en',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'example', home.blocks.simulationexamples.SimulationExampleChooserBlock()), (b'image', home.blocks.images.APIImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_es',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'example', home.blocks.simulationexamples.SimulationExampleChooserBlock()), (b'image', home.blocks.images.APIImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
    ]
