# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='body_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_es',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_es',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
